[package]
name = "amazon_asin_scrape"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.23.1"
serde = "1.0.219"
serde_json = "1.0.140"
